name: Ubuntu with SSH + Tailscale

on:
  workflow_dispatch:

jobs:
  run-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OpenSSH server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Add your SSH public key
        run: |
          mkdir -p ~/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxwyupFObqMZ377b0qim9ayYZv4mTZCtEhfyt2U4bMrEVMHiRHFToPm2FMISI5D2Yv+0uoGgBg1gq7bPHSYajeNtabvi5/lAO9GG9HeokRR3VO/zodB4OeOY7PL5q76ZahEhAvCun9GKQURbgvMPAvsqgIaDG3aBXIdkD1upM3rHerECCd36ayUl15lK0eTD0yURw5SGOmOwB4n4t2FgJHWUtzlhJc+UaUSByAAfy2z4fnRiOBNE8oE/kJVs9agPHobTzEOZtC379rjv8ZxvGKQHiWNBwBazqVLfpk03qStFjiqqOrEMnC/m+zq4/fQFeKGc1fpxWoxJ+1blrQ8ZMr" >> ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --ssh

      - name: Show SSH info
        run: |
          echo "=== SSH Server is running ==="
          echo "Use the following IP to connect from Termius:"
          tailscale ip -4
          echo "Username: runner"
